### ISSUE TITLE
Question on FragmentViewPager

### ISSUE THREAD

**Issue by obipawan** [lsjwzh/RecyclerViewPager#10]
First off, great work! I was checking this library out and works pretty neat :)
From the readme your `todo` has plans for a ```FragmentViewPager``` (can't wait this!! :) )
I was curios on how you'd be implementing it given that the ```RecyclerViewPagerAdapter``` works with recycling ```RecyclerView.ViewHolder``` but what you'd want is a `Fragment` instead? Ideas?
Thanks a ton

**Comment by lsjwzh** [comment]
I want to use a Fragment container  view in RecyclerView.Adpater which support replacing fragment  when position changed.

**Comment by lsjwzh** [comment]
I have implement an FragmentStateViewPager, you can test it on dev branch now.
