### ISSUE TITLE
onPageChanged alternative.

### ISSUE THREAD

**Issue by JonathanMerritt** [lsjwzh/RecyclerViewPager#12]
I'm sorry if this is a dumb question...

I'm attempting to switch over from a VieePager to this library.

However I can't seem to figure out if there is a way to mimic the onPageSelected(int position) method in any of the RecyclerView listeners.

Would you have any advice as to how to get this function with your library.

Thank you.

**Comment by lsjwzh** [comment]
that is a important feature，i think that we can check pagechange on scroll state changed to idle

**Comment by JonathanMerritt** [comment]
I think I understand, but I'm not totally sure.

Would you mind expanding on that a little?

I have something working, but it involves listening for the layout change of the children. Its not perfect and is very inconsistent.

**Comment by JonathanMerritt** [comment]
Just as an update in case anyone else is looking for the same thing, I figured it out.

I just needed to listen for State Idle and get the layoutManager.findFirstavisibleItemPosition() int.

Works perfectly.

Thanks for the guidance and the library @Isjwzh .

**Comment by lsjwzh** [comment]
@JonathanMerritt  i will add this feature as soon as possible， thx for your feed back.

**Comment by lsjwzh** [comment]
I add a listener for this. It that what you want？
 https://github.com/lsjwzh/RecyclerViewPager/tree/dev

**Comment by JonathanMerritt** [comment]
That looks exactly perfect @lsjwzh.

Are you planning on pushing it to maven?

**Comment by JonathanMerritt** [comment]
I grabbed the dev branch and added it locally.

The listener works great. Everything seems to be running very well with it.

Thanks for putting the time in to add it. I appreciate it.

**Comment by lsjwzh** [comment]
If no more bugs were found, i will push it to maven today.
