### ISSUE TITLE
LoopRecyclerViewPager will report a divide zero error when no data

### ISSUE THREAD

**Issue by Kongdy** [lsjwzh/RecyclerViewPager#122]
My app may get data by net.  that will no data when no net or before request data.
so , it will report divide zero ,because data's size is zero.
I debug it.  It occurs mainly in getActualPosition() method.  
And There are Incompatible with baseRecyclerViewAdapterHelper.

**Comment by lsjwzh** [comment]
你好像已经解决了。。。
我把这个close了哈

**Comment by yinyongliang** [comment]
怎么解决的？我也出现这个问题

**Comment by yinyongliang** [comment]
怎么解决的？我也出现这个问题

**Comment by Kongdy** [comment]
拉最新的版本试试
