### ISSUE TITLE
Question: Facebook style pager?

### ISSUE THREAD

**Issue by Anatidae-Project** [lsjwzh/RecyclerViewPager#13]
Nice lib. 

Have you seen how the facebook app will occasionally have a list of horizontal picture/links. You'll have the main one lined up center, but a picture slightly off screen on the right. Swiping reveals the next picture and now you have 3. 

Would I be correct with some sizing settings your lib could mimic that behavior?

**Comment by lsjwzh** [comment]
Setting a larger padding ？？ i will test it.

**Comment by lsjwzh** [comment]
Yes, it works well. You just set a large padding, and dont forget this: android:clipToPadding="false".
But you may need to change FlingFactor and TriggerOffset to improve touching experience
