### ISSUE TITLE
How to have multiple item displayed at once ? 

### ISSUE THREAD

**Issue by Cositdev** [lsjwzh/RecyclerViewPager#137]
Hello !

I'd like to display the current item, and a part of the next one, how can i do that ?
Just like this on a view pager http://stackoverflow.com/questions/13914609/viewpager-with-previous-and-next-page-boundaries

Thank you !

**Comment by yichunyen** [comment]
Here is the basic usage in README

```xml
<com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
    android:id="@+id/list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="15dp"
    android:paddingRight="15dp"
    app:rvp_triggerOffset="0.1"
    app:rvp_singlePageFling="true"
    android:clipToPadding="false"/>
```

Set the paddingRight/Left that you want to use, and set the ```clipToPadding``` attribute 'false'. I hope it will help you to implement the multiple views in RecyclerViewPager.

**Comment by l3il2D** [comment]
How can I make center item bigger that other like your Horizontal example?

**Comment by yichunyen** [comment]
@l3il2D 

Have you read the ```SingleFlingPagerActivity.java``` in app folder? In the example, it told you how to change the ratio to scale your views when scroll the RecyclerViewPager.
