### ISSUE TITLE
小BUG，偶尔滑动不会调用addOnPageChangedListener

### ISSUE THREAD

**Issue by IsSwm** [lsjwzh/RecyclerViewPager#163]
```
//                    添加  页面滑动监听，                   
 mLoopPagerView.addOnPageChangedListener(new RecyclerViewPager.OnPageChangedListener() {
          @Override                       
     public void OnPageChanged(int i, int i1) {                           
         LogUtil.e(i + "i==" + i1);                     
```

**Comment by CJEEP** [comment]
@IsSwm  我也发现了有时候滑动监听不到，你是怎么处理这个问题的？

**Comment by IsSwm** [comment]
@CJEEP   由于我的TabLayout的数量比较少，改成禁止滑动的了。。当时么有找到合适的解决方案。

**Comment by CJEEP** [comment]
@IsSwm 可以用了，我直接用源码修改，就正常了。就是传数据不能用setArguments.

**Comment by IsSwm** [comment]
@CJEEP  嗯，厉害，可以分享一下你的解决办法吗。  传递数据我们可以用其他方法。

**Comment by BaiShou** [comment]
@CJEEP 能否分享一下解决办法

**Comment by CJEEP** [comment]
@IsSwm @BaiShou 你们可以试试不用compile 编译的，直接手动导入aar包，试试看，如果数据量不大的情况，一般没什么影响的。

**Comment by huangchenggang** [comment]
@CJEEP 麻烦下 能否分享一下解决办法 OnPageChanged 有时回调不了

**Comment by wang0826jj** [comment]
@CJEEP 麻烦问以下，怎么解决的

**Comment by ityancs** [comment]
我出现的问题是慢速滑动的时候 OnPageListener 不会被回调，我使用 addOnScrollListener 监测当 RecyclerView state == RecyclerView.SCROLL_STATE_IDLE 时可以认为当前页被选中。

**Comment by lgst** [comment]
我也遇到了，换回1.1.1版本好了

**Comment by lushan1314** [comment]
@lgst 我切换会1.1.1还是不行，你是用的fragmentadapter吗？我这边也是遇到慢慢滑不调用，快速滑动是可以的。

**Comment by lushan1314** [comment]
解决了，用最新版本没这个问题了
