### ISSUE TITLE
No other view can be put before recyclerviewpager?

### ISSUE THREAD

**Issue by rush0621** [lsjwzh/RecyclerViewPager#20]
i have tried to use com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager and some other elements, but no luck, error occured. I found that if there is any viewgroup set before the RecyclerViewPager, it will crash.

 <LinearLayout
        android:id="@+id/test3"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <ImageView
            android:id="@+id/test"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_gravity="left"
            android:contentDescription="@null" />
    </LinearLayout>

    <com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
        android:id="@+id/sliding_viewpager"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:background="@android:color/transparent" />

the above xml layout will give error ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup

**Comment by lsjwzh** [comment]
I have a try. but crash not happened.
Could you try this in my demo ?

**Comment by rush0621** [comment]
I am sorry, look like my project build mixed up old version layout id. Everything looks find after clean project.

**Comment by lsjwzh** [comment]
^_^

**Comment by rush0621** [comment]
hi Isjwzh, it me again, i am sorry. I finally figured out what cause the bug.
since i have a custom view in the same layout, and i created some imageview with custom id 1,2,3,4,....
look like this will cause conflict with your lib. I got my bug fixed after I created an id in values with addition. (e.g. R.id.some_id +1), then the ClassCastException will gone. 

Sorry again for reopen this issue. But I want to help other if anyone fall in this bug.

p.s. sorry for my bad english and long comment

**Comment by lsjwzh** [comment]
omg..that is really a bug...
I use the ids  1,2,3,4 for Fragment Container.
I will change the default ids, or provider an interface to generate ids?
I like the latter one.

**Comment by rush0621** [comment]
I found that we can create unique id in ids.xml like this,
 <item name="some_id" type="id" />

this way can only ensure this id is unique, but not for all ids if we create id in a loop with +1, +2, +3, there is still a chance to create a bug. if you find a better way, please tell me :)

**Comment by lsjwzh** [comment]
https://github.com/lsjwzh/RecyclerViewPager/commit/56d9d20934e95b030571269de2909ae480119ea5
I try to do this. It may work well.
