### ISSUE TITLE
LayoutAdapter not recognized by Android Studio

### ISSUE THREAD

**Issue by sDurgam** [lsjwzh/RecyclerViewPager#21]
I am running into errors in my Android Studio like LayoutAdapter, RecyclerViewEx not recognized. I included compile('com.lsjwzh:recyclerviewpager:1.0.4') in my grade file. I want to know if I am missing something.
..Regards
Durga.

**Comment by lsjwzh** [comment]
Do you upgrade recycleviewpage from  v0.5.x?
i have reimplemented recyclerviewpager at 1.0.4.
The new version inherit official RecyclerView instead of RecyclerViewEx.

**Comment by sDurgam** [comment]
Yes I added compile 'com.lsjwzh:recyclerviewpager:1.0.4' to app gradle file. LayoutAdapter and updateState methods are not resolved. Attached is a screenshot for reference.
![recyclerviewpager](https://cloud.githubusercontent.com/assets/3854768/8531831/e7f4ea7c-23de-11e5-94f3-161d0609143f.png)

**Comment by lsjwzh** [comment]
LayoutAdapter is a ListAdapter implementation which should be implemented by yourself.You can also take a look at the demo code.
I will update readme to explain it.
