### ISSUE TITLE
Question: How to reliably get the previous and next position of the currently visible position?

### ISSUE THREAD

**Issue by JonathanMerritt** [lsjwzh/RecyclerViewPager#22]
What I'd like to figure out is, if it is possible to always know what the next position will be and what the previous position was.

My case;

I'm using this as a gallery for images, using the currently visible images bitmap to generate a palette and use that to color my UI.

Doing so works great, however on page change the palette takes at least 3 or so seconds to generate and change.

So I was thinking if I could always grab the image for the last visible and next visible position, I can maybe do some of that work before the actual page change. 

Any advice would be greatly appreciated.
Thanks.

**Comment by JonathanMerritt** [comment]
I actually figured out a much better way to setup my Palette, and I don't really need this anymore.

Sorry for the needless clutter.

**Comment by lsjwzh** [comment]
^_^
