### ISSUE TITLE
How to use when migrate to AndroidX?

### ISSUE THREAD

**Issue by huyvm** [lsjwzh/RecyclerViewPager#227]
My profile show error: java.lang.IllegalAccessError: Field 'androidx.recyclerview.widget.RecyclerView$ViewHolder.mPosition' is inaccessible to class 'androidx.appcompat.widget.ViewHolderDelegate' (declaration of 'androidx.appcompat.widget.ViewHolderDelegate'

**Comment by bctpl** [comment]
did you can please tell me solution?

**Comment by huyvm** [comment]
Hi, You can pref my fork. I was migrate to androidX. See here: https://github.com/huyvm/RecyclerViewPager

**Comment by bctpl** [comment]
@huyvm In My lib I can't get **ViewHolderDelegate** using `import androidx.recyclerview.widget.ViewHolderDelegate;`  so please tell me how to get that .. and thanks for fast reply

**Comment by huyvm** [comment]
Hi @bctpl, remove old implement and add my RecyclerViewPager (read ReadMe).

**Comment by bctpl** [comment]
I don't have any old implementation of that library I downloaded and convert into androidx that's it and I have all that library implementation but still can't resolve that and **ViewHolderDelegate**  it's declaration also not in `androidx.recyclerview.widget` when i dig into library

**Comment by bctpl** [comment]
@huyvm Your repo work but how you do that please let me explain if possible why I can't get **ViewHolderDelegate**  in my implement ?

**Comment by huyvm** [comment]
Hi, because RecyclerViewPaper in your implement don't support migrate to AndroidX.

**Comment by bctpl** [comment]
Your forked implementation worked perfectly thanks for that. But still confused why  **RecyclerViewPaper in your implement don't support migrate to AndroidX.** not working. Anyway thanks for helping ☺

**Comment by huyvm** [comment]
Hi, because https://github.com/lsjwzh/RecyclerViewPager don't yet convert repos to androidX. So when you use with implement from lsjwzh/RecyclerViewPager, you will see error.
