### ISSUE TITLE
How to show 3 views vertical?

### ISSUE THREAD

**Issue by GuyDviri** [lsjwzh/RecyclerViewPager#24]

**Comment by lsjwzh** [comment]
You can do it just need to change the padding :  

    <com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
        android:id="@+id/list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:paddingTop="250dp"
        android:paddingBottom="250dp"/>

**Comment by lsjwzh** [comment]
And then you can see this :   

![screenshot_2015-07-18-16-19-41 0](https://cloud.githubusercontent.com/assets/2450938/8760930/ef1c97a2-2d69-11e5-990b-c14c86c77f46.png)

**Comment by lsjwzh** [comment]
But you also need to change the TriggerOffset and FlingFactor into an appropriate value.
like this:
        mRecyclerView.setTriggerOffset(0.5f);
        mRecyclerView.setFlingFactor(0.25f);

**Comment by GuyDviri** [comment]
Thanks you very much that's great !

**Comment by ibrahim132** [comment]
How to show 3 views horizontal without adding extra white spaces ?
