### ISSUE TITLE
Question: onPageScrolled(..., float positionOffset, ...)?

### ISSUE THREAD

**Issue by JonathanMerritt** [lsjwzh/RecyclerViewPager#25]
What would be the best way to achieve a similar return with this library?

If it is in fact possible of course.

Thank You,
Jon.

**Comment by lsjwzh** [comment]
I am considering this API,but i really think that official ViewPager's api is a little bad.
You can do same action like this  in 'onScroll' block :  
                 int width = mRecyclerView.getChildAt(0).getWidth();
                int padding = (mRecyclerView.getWidth() - width) / 2;

                View curView = ViewUtils.getCenterXChild(mRecyclerView);
                if(curView!=null) {
                    int offset = padding - curView.getLeft();
                    // if scroll left ， offset > 0 ； scroll right ，offset < 0
                }

**Comment by lsjwzh** [comment]
I think this is important API,i will add it next version.if you have done this, welcome to send PR.

**Comment by JonathanMerritt** [comment]
Very very sorry for not responding at all. Been busy, but I'm gonna be trying this out tonight. If it's successful I'll let you know, however I doubt I'll be able to write it into your code. I'm just not at that level yet, code wise.

**Comment by lsjwzh** [comment]
It's really not so hard. Just have a try. ^_^
