### ISSUE TITLE
QUESTION:when I add on my gradle file,build failed

### ISSUE THREAD

**Issue by DankeLuo** [lsjwzh/RecyclerViewPager#27]
and  i am getting following error while building my app:
..../values/colors.xml:
    Error:Attribute "textAllCaps" has already been defined
    Error:Attribute "theme" has already been defined

**Comment by lsjwzh** [comment]
It may be appcompat-v7 conflict.
You can try this:
compile('com.lsjwzh:recyclerviewpager:1.0.7-SNAPSHOT'){
        exclude module: 'appcompat-v7'
        exclude module: 'recyclerview-v7'
    }
