### ISSUE TITLE
Question.. Horizontal Recyclerviewpager holding cardview not showing next card hint

### ISSUE THREAD

**Issue by a-latta** [lsjwzh/RecyclerViewPager#28]
I am following the horizontal layout example and using Cardview as my recyclerview items. Like the example shows,I don't see the next card as a hint for user to scroll horizontally. Am I missing something?

**Comment by lsjwzh** [comment]
next card hint?
Do you mean the padding??
You can define padding like this:
<com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
    android:id="@+id/list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="15dp"
    android:paddingRight="15dp"
    android:clipToPadding="false"/>

by setting this attr "android:paddingLeft" "android:paddingRight".
You will see next and prev card.

**Comment by a-latta** [comment]
I want the user to know that the view is Horizontally scrollable, I want to show the cards on right edge of the screen kind of hinting that there are more cards.I have added padding but still my RecyclerViewPager  shows the card and a lot of whitespace on both left and right side. Not sure if it is the cardview that is adding extra padding around or its the RecyclerViewPager.

**Comment by lsjwzh** [comment]
So ?  how did you solve it？
