### ISSUE TITLE
Enable child scroll

### ISSUE THREAD

**Issue by iGio90** [lsjwzh/RecyclerViewPager#29]
Hello, I'm using your library to create a vertical pager with a custom recyclerview adapter that inflate other recyclerviews and scrollviews. I can't figure out a way to enable the scroll on childs that is not working actually. Do you know any solution for this? thank you!

**Comment by lsjwzh** [comment]
That  is really a trouble.
I think you should try NestedScrollView.
https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html

**Comment by lsjwzh** [comment]
Maybe,you need create a new class which implements NestedScrollingParent and extends RecyclerViewPager.
