### ISSUE TITLE
swapAdapter not overridden

### ISSUE THREAD

**Issue by vernazza** [lsjwzh/RecyclerViewPager#31]
The swapAdapter function is not overridden, so if you try to call it, it will replace it will replace RecyclerViewPagerAdapter instead of the contained Adapter

**Comment by lsjwzh** [comment]
https://github.com/lsjwzh/RecyclerViewPager/commit/29631fa2c3a1d495464a5b3b532e434df6cab3c3

**Comment by lsjwzh** [comment]
Thanks for your feedback.
