### ISSUE TITLE
1.0.8 aar in maven repository have problem

### ISSUE THREAD

**Issue by lyrixliu** [lsjwzh/RecyclerViewPager#38]
I wrote a project using your lib, when package release variant, proguard fail, and print the following errors:
>> Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'int access$102(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager,int)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
>> Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'float access$202(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager,float)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
>> Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'float access$300(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
>> Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'int access$400(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager,int,int)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
>> Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'int access$500(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
>> Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'int access$100(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
>> Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'java.util.List access$600(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
>> Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'android.support.v7.widget.RecyclerView$OnScrollListener access$700(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager

I thought maybe you forgot to clean project before assembling the aar file.

Hope this bug could be fixed!

**Comment by lsjwzh** [comment]
Your RecyclerView version？？

**Comment by lyrixliu** [comment]
22.2.1

**Comment by wonTonx** [comment]
I have the same problem too
22.2.1 RecyclerView version

**Comment by wonTonx** [comment]
I change the version back to 1.0.6 is OK

**Comment by filbertteo** [comment]
I encountered the same problem as well. Tried using v22.2.0 for the RecyclerView support library, but the problem still occurs. Had to resort to downloading and adding the module manually in Android Studio instead of using the Maven repository. Thankfully that works :)

**Comment by lsjwzh** [comment]
Does 1.0.10-SNAPSHOT  resolved this problem??

**Comment by lsjwzh** [comment]
@filbertteo @wonTonx @lyrixliu

**Comment by filbertteo** [comment]
@lsjwzh just tested. still has the problem. build log is as follows:

Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'int access$102(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager,int)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'float access$202(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager,float)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'float access$300(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'int access$400(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager,int,int)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'int access$500(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'int access$100(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'java.util.List access$600(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'android.support.v7.widget.RecyclerView$OnScrollListener access$700(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager
Warning: com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager$ScrollListener: can't find referenced method 'java.util.List access$800(com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager)' in program class com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager

**Comment by lsjwzh** [comment]
@filbertteo Could you post your build.gradle?

**Comment by filbertteo** [comment]
```
repositories {
    mavenCentral()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

dependencies {
    // RecyclerViewPager library
    compile('com.lsjwzh:recyclerviewpager:1.0.10-SNAPSHOT')
}
```

**Comment by lsjwzh** [comment]
@filbertteo  your build options? ex.... lintOption and so on....

**Comment by lsjwzh** [comment]
@filbertteo @wonTonx @lyrixliu
Adding the line below into proguard  file will resolve it.
-dontwarn com.lsjwzh.widget.recyclerviewpager.**


It is just a warn info.
http://stackoverflow.com/questions/23883028/how-to-fix-proguard-warning-cant-find-referenced-method-for-existing-methods

**Comment by vishuhm911** [comment]
i am getting - failed to resolve failed to resolve com.github.lsjwzh.RecyclerViewPager:lib:v1.1.0
