### ISSUE TITLE
Android studio cannot import by gradle

### ISSUE THREAD

**Issue by huaxiaogood** [lsjwzh/RecyclerViewPager#4]
Hi,

Android studio cannot import by gradle

when i add compile('com.lsjwzh:recyclerviewpager:0.1.0-RELEASE') into gradle,and sync it

then,android studio show me:

![image](https://cloud.githubusercontent.com/assets/8043228/6521179/caf9eac4-c40e-11e4-8ae7-76fd04f6047b.png)

**Comment by lsjwzh** [comment]
sorry,i am not update the doc  in time,the latest version is 0.5，
`compile('com.lsjwzh:recyclerviewpager:0.5.0')`   this will work well.

**Comment by lsjwzh** [comment]
in fact,the lib is waiting for release in maven repo,that may spend few hours
