### ISSUE TITLE
scrollToPosition

### ISSUE THREAD

**Issue by MTJH** [lsjwzh/RecyclerViewPager#47]
when use scrollToPosition， Infinite-Loop-ViewPager is not work

**Comment by lsjwzh** [comment]
I will check it.

**Comment by lsjwzh** [comment]
I have resolve it at 1.1.0-beta2
https://github.com/lsjwzh/RecyclerViewPager/releases/tag/v1.1.0-beta2

**Comment by lsjwzh** [comment]
But you should use LoopRecyclerViewPager instead of RecyclerViewPager with isLoopEnable method.
