### ISSUE TITLE
issue loop

### ISSUE THREAD

**Issue by myscreen** [lsjwzh/RecyclerViewPager#48]
Hi I used RVPager in fragmentviewpager. when I enable the loop, I can only flip to left because flip to right changes the tap to next tab. Can you help me to fix it? 
Thanks and Best Regards

**Comment by lsjwzh** [comment]
I  will check it

**Comment by lsjwzh** [comment]
Do you mean this ?
https://github.com/nshmura/RecyclerTabLayout

**Comment by myscreen** [comment]
no, i mean in your project when I enable the infinity loop, the user cant flip on right side, it can be flipped on left side. on the right it changes the tabs.

**Comment by lsjwzh** [comment]
What is  “it changes the tabs” ？ 
Does  "tabs"  mean TabLayout or others ?
Could you give me  some code or snapshot ?

**Comment by lsjwzh** [comment]
Do you mean that right side is more sensitive than left ?

**Comment by myscreen** [comment]
hi
![flippingissue](https://cloud.githubusercontent.com/assets/14212198/11803982/dd0e3f56-a33a-11e5-8762-6374b8cbe14b.png)

According to the above image, I use your pager in my adapter header. everything is fine however when I enable app:rvp_loopEnabled="true", the swipe to left it works well. when I swipe right, the arrow 2, the ViewPager is changed to the next one. The viewpager swipe to right. It is an issue. 
At the end, when the loop is disable, the both swipes are working as charm. Thanks for your Best Supports

**Comment by lsjwzh** [comment]
May be the latest version have resolved this.
You can try it. But you need to use LoopRecyclerViewPager instead of RecyclerViewPager.

**Comment by myscreen** [comment]
hi
sorry for late respond. I try but it is so sensetive. can you inform me how I can decrease the degree of sensetivness. When I wanna swipe, the viewpager is changed to next fragment completly.

**Comment by myscreen** [comment]
hi
getCurrentPosition is not working in loop. It returns incorrect number. ;(

**Comment by lsjwzh** [comment]
It may be resolved at 1.1.0 stable release.
