### ISSUE TITLE
How to setOnItemClickListener?

### ISSUE THREAD

**Issue by huaxiaogood** [lsjwzh/RecyclerViewPager#5]
Sorry, I cannot find the ways to setOnItemClickListener

**Comment by huaxiaogood** [comment]
setDisplayPadding?

**Comment by huaxiaogood** [comment]
Ha，I find another way to setOnItemClickListener，Thanks ~~

**Comment by lsjwzh** [comment]
e....How ??

**Comment by huaxiaogood** [comment]
e......when i init child view, i set the view's onClickListener......ha,i cannot find other solutions ~.~
