### ISSUE TITLE
你好，请问如何设置，才能让其自动滚动。

### ISSUE THREAD

**Issue by hedge-hog** [lsjwzh/RecyclerViewPager#51]
你好，请问如何设置，才能让其自动滚动，谢谢！

**Comment by lsjwzh** [comment]
可以参考这种方式，让其自动翻页。
https://github.com/Trinea/android-auto-scroll-view-pager/blob/master/src/cn/trinea/android/view/autoscrollviewpager/AutoScrollViewPager.java

**Comment by hedge-hog** [comment]
多谢，已经找到一种方法来解决自动滚动的问题！：）

**Comment by verticalakash** [comment]
Hi @lsjwzh  could you please share how can i use this class with RecyclerViewPager.
