### ISSUE TITLE
Is it possible to have vertical RecyclerViewPager with two items(pages) on one screen?

### ISSUE THREAD

**Issue by tatyana-parnyuk** [lsjwzh/RecyclerViewPager#53]
Is it possible to have vertical RecyclerViewPager with two items(pages) on one screen?

**Comment by lsjwzh** [comment]
I think it is possible.

**Comment by lsjwzh** [comment]
I will try and confirm it.

**Comment by tatyana-parnyuk** [comment]
Thank you, let me know the results.

**Comment by lsjwzh** [comment]
Yes.You just need to set a large padding for this.
![image](https://cloud.githubusercontent.com/assets/2450938/12359360/faf590c6-bbec-11e5-8a13-fcf9c94076d1.png)

**Comment by tatyana-parnyuk** [comment]
thanks, it works

**Comment by ibrahim132** [comment]
What about horizontal view pager. I want to show 3 items on one screen ?
