### ISSUE TITLE
Is it possible to use LoopRecyclerViewPager in Material Demo?

### ISSUE THREAD

**Issue by jasonni** [lsjwzh/RecyclerViewPager#54]
Hi @lsjwzh , is it possible to use LoopRecyclerViewPager in Material Demo?
I did it but throw  java.lang.IndexOutOfBoundsException: Invalid index 1073741820, size is 10

thanks.

**Comment by lsjwzh** [comment]
It is possible. But i should modify some code in TabLayoutSupport lib to support LoopRecyclerViewPager

**Comment by lsjwzh** [comment]
I have resolve this exception in 1.1.0-beta5.
But the official TabLayout lib have not loop effect.
