### ISSUE TITLE
Divider not working correctly

### ISSUE THREAD

**Issue by cemalper** [lsjwzh/RecyclerViewPager#55]
Hi, I read this page https://github.com/lsjwzh/RecyclerViewPager/issues/45 and i added a divider from your link. But when I change page divider still visible and if I go to previous page divider invisible. How can I fix it 
Because normally it should be like page 0 like below the image, not page 1

![1](https://cloud.githubusercontent.com/assets/7502686/12523929/782bccca-c162-11e5-8afa-5528e20eff24.png)
![0](https://cloud.githubusercontent.com/assets/7502686/12523936/7b697450-c162-11e5-9622-d96bdc18633a.png)
![3](https://cloud.githubusercontent.com/assets/7502686/12523954/8f3378d2-c162-11e5-96e9-58a9936ed66b.png)

my divider xml
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
       android:shape="rectangle">

    <size
        android:width="10dp"
        android:height="10dp" />

    <solid android:color="#ff0000" />

</shape>
```
Thanks

**Comment by lsjwzh** [comment]
I have fix it in v1.1.0-beta4, you can try it.
