### ISSUE TITLE
Anybody else experiencing memory issues?

### ISSUE THREAD

**Issue by MarsVard** [lsjwzh/RecyclerViewPager#57]
After removing fragment that contains the recyclerview, the memory is not freed.

**Comment by lsjwzh** [comment]
Mem Trace File ？
Or snapshot？
The memory is not freed ，even though you run gc manually？

**Comment by cperry-gpsw** [comment]
Calling `System.gc()` will **not** fix a memory leak. Are you statically holding onto a `Context` anywhere in the library?

**Comment by lsjwzh** [comment]
I will check it. What about just use normal recycerview?

**Comment by lsjwzh** [comment]
May be this is the reason ? https://github.com/lsjwzh/RecyclerViewPager/pull/72
