### ISSUE TITLE
Calling getLayoutManager().canScrollHorizontally when getLayoutManager() is null.

### ISSUE THREAD

**Issue by ethanschreiber** [lsjwzh/RecyclerViewPager#58]
I am using your RecyclerViewPager within the Umano AndroidScrollingUpPanel. (https://github.com/umano/AndroidSlidingUpPanel). I am getting the following error:

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollHorizontally()' on a null object reference
    at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.dispatchTouchEvent(RecyclerViewPager.java:384)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
    ...

This is called when the Umano's dispatchTouchEvent returns   super.dispatchTouchEvent(ev);

    at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SlidingUpPanelLayout.java:1035)

The fix was very easy for me. Here is your original code within RecyclerViewPager.java:

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (ev.getAction() == MotionEvent.ACTION_DOWN) {
            mPositionOnTouchDown = getLayoutManager().canScrollHorizontally()
                    ? ViewUtils.getCenterXChildPosition(this)
                    : ViewUtils.getCenterYChildPosition(this);
            if (DEBUG) {
                Log.d("@", "mPositionOnTouchDown:" + mPositionOnTouchDown);
            }
        }
        return super.dispatchTouchEvent(ev);
    }

I changed this as following by simply making sure getLayoutManager is not null:

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (ev.getAction() == MotionEvent.ACTION_DOWN) {

            if (getLayoutManager() != null) {              // *** CHANGE IS HERE! ***
                mPositionOnTouchDown = getLayoutManager().canScrollHorizontally()
                                       ? ViewUtils.getCenterXChildPosition(this)
                                       : ViewUtils.getCenterYChildPosition(this);
            }
            if (DEBUG) {
                Log.d("@", "mPositionOnTouchDown:" + mPositionOnTouchDown);
            }
        }
        return super.dispatchTouchEvent(ev);
    }

It now works. Do you have any thoughts on this? Is what I did just a hack? Is it a good idea?

**Comment by asadqazi** [comment]
I am facing the same issue. Is there any solution?

**Comment by muximus3** [comment]
i solve this by adding recyclerViewPager manual in code , not .xml.  cause when in .xml any touch would lead a crash before we set the "LayoutManager" for recyclerViewPager.
