### ISSUE TITLE
开源组件android-auto-scroll-view-pager遇到的一些问题

### ISSUE THREAD

**Issue by jact-hz** [lsjwzh/RecyclerViewPager#7]
您好。您上次在github上回复我的
@Override
public boolean dispatchTouchEvent(MotionEvent event) {
    boolean inBannerArea = isInBannerArea(event);
    if ((event.getAction() == MotionEvent.ACTION_DOWN
            && inBannerArea) || mActionDownOnBannerArea) {
        //如果在banner区域按下，则开始触发bannerViewPager的ontouch事件
        mActionDownOnBannerArea = true;
        try {
            mBannerViews.bannerViewPager.onTouchEvent(event);
        } catch (IllegalStateException e) {

        }
    }
    if (event.getAction() == MotionEvent.ACTION_UP) {
        mActionDownOnBannerArea = false;
        mBannerViews.bannerViewPager.startAutoScroll();
    }
    return false;
}
isInBannerArea(event)和mBannerViews.bannerViewPager 找不到？
还有一个问题就是我下拉刷新的时候想修改展示的图片数量,然后让图片跳转到第一张该怎么改呢。
修改数据源 调用adapter.notifyDataSetChanged();刷新没效果呢。

**Comment by lsjwzh** [comment]
mBannerViews.bannerViewPager 就是你再activty里面的 ViewPager 对象。
/**
     * 首页横幅的初始位置，用于判断touch事件是否在横幅区域内
     */

    int[] bannerInitialLocation = new int[2];


/**
     * 是否在横幅区域
     *
     * @param ev
     * @return
     */
    boolean isInBannerArea(MotionEvent ev) {
        int[] location = new int[2];
        //第一次触摸时获取横幅的初始位置
        if (bannerInitialLocation[1] == 0) {
            mBannerViews.bannerViewPager.getLocationOnScreen(bannerInitialLocation);
        }
        mBannerViews.bannerViewPager.getLocationOnScreen(location);
        int yStart = bannerInitialLocation[1];
        int yEnd = location[1] + mBannerViews.bannerViewPager.getHeight();
        if (yEnd < yStart) {
            return false;
        }
        //若触摸时y坐标在横幅范围内，则返回true
        return (ev.getRawY() <= yEnd && ev.getRawY() >= yStart);
    }

**Comment by lsjwzh** [comment]
·修改数据源 调用adapter.notifyDataSetChanged();刷新没效果呢。·
你是在主线程调用的么？
我一般都是这样操作：
···
  mBannerViews.bannerViewPager.removeAllViews();

        mBannerViews.bannerViewPager.setAdapter(bannerViewAdapter);
···

**Comment by jact-hz** [comment]
更新解决了,谢谢。
但是android-auto-scroll-view-pager中的图片上下拉的时候,仍然不能使使外围的mPullRefreshScrollView滑动
