### ISSUE TITLE
Going to Infinite Scroll.

### ISSUE THREAD

**Issue by dalwadi2** [lsjwzh/RecyclerViewPager#73]
`mRecyclerViewPager.smoothScrollToPosition(position);`

When I am going to apply this code in onCreate then it will be Infinite scroll happens.
suggest me the solution ASAP. @lsjwzh

**Comment by lsjwzh** [comment]
You can call smoothScrollToPosition like this :

        mRecyclerView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                mRecyclerView.getViewTreeObserver().removeGlobalOnLayoutListener(this);
                mRecyclerView.smoothScrollToPosition(position);
            }
        });

**Comment by dalwadi2** [comment]
Thank you @lsjwzh .
but this method is deprecated : 
`removeGlobalOnLayoutListener`
is it okay ??
and you can close issue.

**Comment by lsjwzh** [comment]
Dont worry it. If you do not like that warning, you can do it like this:
if (api > 16) {
removeOnGlobalLayoutListener....
} else {
removeGlobalOnLayoutListener...
}

**Comment by BongJaeChoi** [comment]
@lsjwzh It is not working your sugeested code
