### ISSUE TITLE
LoopRecyclerViewPager getitem

### ISSUE THREAD

**Issue by dainixiao** [lsjwzh/RecyclerViewPager#74]
Log  -->getItem:1073741822 from cachetrue

position  1073741822  

这个position怎么弄成0,1,2,3,4?而不是拿的view 的id 值
没有使用TabLayout

**Comment by lsjwzh** [comment]
#### How to get actual position in LoopRecyclerViewPager:
```
    int actualPosition = mLoopRecyclerViewPager.transformToActualPosition(adapterPosition);
```
If you just want to get current actual position, you can do it like this:

```
    int actualCurrentPosition = mLoopRecyclerViewPager.getActualCurrentPosition();
```
