### ISSUE TITLE
Non stop spinning when using LoopRecyclerViewPager

### ISSUE THREAD

**Issue by arvydaszenitech** [lsjwzh/RecyclerViewPager#77]
Hi, 
sometimes when i swipe it starts spinning endlessly. Looks like sometimes it fails to snap scrolled item. When i tap on it, it stops spinning. It's hard to reproduce it, but it happens from time to time. Any one else experienced that?

**Comment by lsjwzh** [comment]
I will check it.

**Comment by dadu1** [comment]
Hi @arvydaszenitech  mRecyclerViewPager.setFlingFactor(0.05f); this may help you by reducing fling factor you can over come from this issue.

**Comment by lsjwzh** [comment]
It may be resolved at 1.1.0 stable release
