### ISSUE TITLE
Layout issue when recyclerview dependency is higher than 23.1.1 !

### ISSUE THREAD

**Issue by afaucogney** [lsjwzh/RecyclerViewPager#81]
I spent a long time figuring out which dependency version has causing me this trouble.

I use the version 1.0.8, because the layout changed since this version in my use case.

Recently, I upgraded other libs, and a strange behavior happened:
- I do not see the RecyclerViewPager items (like they get size of 0 or sometimes very small)
- The first items is bigger than other (instrinsec size are the same for every items). If I update the adapter, then it come back as it should.

I had to force the dependency to 23.1.1 to ensure the expected behavior. 

In my app build.gradle (for other who may be interested)

configurations.all {
        resolutionStrategy.force 'com.android.support:recyclerview-v7:' 23.1.1
}

Do you have any "idea" or "change done" in mind that would be linked to this ?

**Comment by lsjwzh** [comment]
May be you should update to latest veision.
