### ISSUE TITLE
How to add tabs to this?

### ISSUE THREAD

**Issue by arshad115** [lsjwzh/RecyclerViewPager#9]
How do you add pagertitlestrip or tabstrip with this?

**Comment by lsjwzh** [comment]
I use a deprecated api of  SupportActionBar.

ActionBar actionBar = getSupportActionBar();
        actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);
        actionBar.setDisplayShowTitleEnabled(false);
        actionBar.setDisplayShowHomeEnabled(false);

        ActionBar.Tab tab = actionBar.newTab()
                .setText("Horizontal")
                .setTabListener(new TabListener(HorizontalLayoutFragment.class, "Horizontal"));
        ActionBar.Tab tab2 = actionBar.newTab()
                .setText("Vertical")
                .setTabListener(new TabListener(VerticalLayoutFragment.class, "Vertical"));
        actionBar.addTab(tab, true);
        actionBar.addTab(tab2, false);
