### ISSUE TITLE
在为tv应用开发时，发现不支持dpad按键滑动

### ISSUE THREAD

**Issue by olivine13** [lsjwzh/RecyclerViewPager#92]
作者您好，我是一名android tv的开发者，其中有个项目因为一些原因使用了您的开源项目
在使用中，发现控件本身做的非常棒，然而美中不足的是和viewpager还是有些差别，主要是针对于dpad的操控并不支持(viewpager已经对按键事件进行了拦截)
于是我在原本代码上做了一些修改，主要参考自viewpager的executeKeyEvent方法，使得在tv应用上也能用dpad去滑动recyclerview
不知道这个功能是否有必要进入进去呢

**Comment by lsjwzh** [comment]
非常有必要。。欢迎提交pr。
